import { Injectable, HttpException, HttpStatus, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { ProjectsService } from '../projects/projects.service';
import OpenAI from 'openai';

@Injectable()
export class AiService {
  private readonly logger = new Logger(AiService.name);
  private openai: OpenAI;

  constructor(
    private configService: ConfigService,
    private projectsService: ProjectsService,
  ) {
    const apiKey = this.configService.get<string>('OPENAI_API_KEY');
    if (!apiKey) {
      this.logger.warn('OPENAI_API_KEY is missing. AI functionality will fail.');
    }
    this.openai = new OpenAI({ apiKey: apiKey || 'dummy-key' });
  }

  async generateAndInjectTasks(
    prompt: string,
    projectId: string,
    userId: string,
    userEmail: string,
    columnId?: string
  ) {
    if (this.openai.apiKey === 'dummy-key' || !this.openai.apiKey) {
       throw new HttpException('API Key de OpenAI no configurada en el archivo .env del servidor.', HttpStatus.INTERNAL_SERVER_ERROR);
    }

    try {
      // Get the project to ensure user has access
      const project = await this.projectsService.findOne(projectId, userId, userEmail);

      // Respect the per-project AI toggle.
      if ((project as any).aiEnabled === false) {
        throw new HttpException('La generación con IA está deshabilitada para este proyecto.', HttpStatus.FORBIDDEN);
      }

      // Default to the first column (e.g. "To Do") if not provided
      const targetColumnId = columnId || project.columnOrder[0] || 'column-todo';

      // Call OpenAI to structure tasks
      const completion = await this.openai.chat.completions.create({
        model: this.configService.get<string>('OPENAI_MODEL') || 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: `You are an expert product manager and software architect. 
Break down the user's request into smaller, actionable Kanban tasks.
Always respond in JSON matching the exact schema provided. Do not use markdown blocks around the JSON.`
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        response_format: { type: "json_object" },
        tools: [
          {
            type: "function",
            function: {
              name: "generate_tasks",
              description: "Generates a list of tasks",
              parameters: {
                type: "object",
                properties: {
                  tasks: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        title: { type: "string", description: "A concise, actionable task title" },
                        description: { type: "string", description: "Detailed description of what needs to be done" },
                        priority: { type: "string", enum: ["low", "medium", "high"] }
                      },
                      required: ["title", "description", "priority"]
                    }
                  }
                },
                required: ["tasks"]
              }
            }
          }
        ],
        tool_choice: { type: "function", function: { name: "generate_tasks" } }
      });

      const toolCall = completion.choices[0]?.message?.tool_calls?.[0];
      if (!toolCall || toolCall.type !== 'function') {
        throw new Error('Failed to generate tasks structure.');
      }

      const args = JSON.parse(toolCall.function.arguments);
      const generatedTasks = args.tasks || [];

      if (generatedTasks.length === 0) {
        throw new Error('No tasks were generated by AI.');
      }

      // Inject into project
      project.tasks = project.tasks || {};
      if (!project.columns[targetColumnId]) {
         project.columns[targetColumnId] = { id: targetColumnId, title: "To Do", taskIds: [] };
         if (!project.columnOrder.includes(targetColumnId)) {
            project.columnOrder.push(targetColumnId);
         }
      }

      // Add a small delay between IDs to ensure sorting consistency if needed
      for (const t of generatedTasks) {
        const taskId = `task-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`;
        project.tasks[taskId] = {
          id: taskId,
          title: t.title,
          description: t.description,
          priority: t.priority || 'medium',
          tags: ['AI-Generated'],
          subtasks: [],
          comments: [],
          dueDate: '',
          createdAt: new Date().toISOString()
        };
        project.columns[targetColumnId].taskIds.push(taskId);
      }

      await this.projectsService.update(projectId, userId, userEmail, project);

      return { 
        success: true, 
        message: `Se han generado e inyectado ${generatedTasks.length} tareas nuevas.`,
        generatedCount: generatedTasks.length,
        project: project
      };

    } catch (error: any) {
      if (error instanceof HttpException) throw error;
      this.logger.error(`Error generating tasks: ${error.message}`);
      throw new HttpException(error.message || 'Error al conectar con OpenAI', HttpStatus.INTERNAL_SERVER_ERROR);
    }
  }
}
